### ISSUE TITLE
rows below the check-calendar row does not align well using padding as checkbox-width changes from os to os

### ISSUE THREAD

**Issue by arshdkhn1** [arshdkhn1/gsoc17-convert-xul-to-html#11]
found a solution that's not very elegant but works 100% fine along all OS. 
```css
.row:not(.no-left-padding):before {
  content: ' ';
  -moz-appearance: checkbox;
  flex: none;
  margin-right: 5px;
  opacity: 0;
  visibility: hidden;
}
```

Openin this issue, to find a better solution maybe
