### ISSUE TITLE
splitter changes groupbox width below fieldset min-width in mac or maybe linux too

### ISSUE THREAD

**Issue by arshdkhn1** [arshdkhn1/gsoc17-convert-xul-to-html#17]

**Comment by arshdkhn1** [comment]
solved by doin 
```css

.row > .row-input {
  flex: 1 0 10px; 
...
}
```
